build:
	g++ --std=c++11 -Wall -Wextra bani.cpp -o bani
	g++ --std=c++11 -Wall -Wextra gard.cpp -o gard
	g++ --std=c++11 -Wall -Wextra bomboane.cpp -o bomboane
	g++ --std=c++11 -Wall -Wextra sala.cpp -o sala

run-p1:
	./bani

run-p2:
	./gard

run-p3:
	./bomboane
	
run-p4:
	./sala
	
clean:
	rm -f bani gard bomboane sala
